version: "3"

services:
  app:
    image: hub.narasimman.xyz/laravel-app:1.1.6
    build:
      context: ../laravel-app
      dockerfile: Dockerfile
    container_name: laravel-app
    networks:
      - laravel-network
    ports:
      - 80:8000

networks:
  laravel-network:
    external: true
